/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QrRouteImport } from './routes/qr'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StopwatchRouteImport } from './routes/stopwatch'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as TimetableRouteImport } from './routes/timetable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StopwatchRoute = StopwatchRouteImport.update({
  id: '/stopwatch',
  path: '/stopwatch',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/assignments': typeof AssignmentsRoute
  '/attendance': typeof AttendanceRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/holidays': typeof HolidaysRoute
  '/notes': typeof NotesRoute
  '/projects': typeof ProjectsRoute
  '/qr': typeof QrRoute
  '/settings': typeof SettingsRoute
  '/stopwatch': typeof StopwatchRoute
  '/subjects': typeof SubjectsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/assignments': typeof AssignmentsRoute
  '/attendance': typeof AttendanceRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/holidays': typeof HolidaysRoute
  '/notes': typeof NotesRoute
  '/projects': typeof ProjectsRoute
  '/qr': typeof QrRoute
  '/settings': typeof SettingsRoute
  '/stopwatch': typeof StopwatchRoute
  '/subjects': typeof SubjectsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/assignments': typeof AssignmentsRoute
  '/attendance': typeof AttendanceRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/holidays': typeof HolidaysRoute
  '/notes': typeof NotesRoute
  '/projects': typeof ProjectsRoute
  '/qr': typeof QrRoute
  '/settings': typeof SettingsRoute
  '/stopwatch': typeof StopwatchRoute
  '/subjects': typeof SubjectsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/assignments'
    | '/attendance'
    | '/exams'
    | '/expenses'
    | '/holidays'
    | '/notes'
    | '/projects'
    | '/qr'
    | '/settings'
    | '/stopwatch'
    | '/subjects'
    | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/assignments'
    | '/attendance'
    | '/exams'
    | '/expenses'
    | '/holidays'
    | '/notes'
    | '/projects'
    | '/qr'
    | '/settings'
    | '/stopwatch'
    | '/subjects'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-chat'
    | '/assignments'
    | '/attendance'
    | '/exams'
    | '/expenses'
    | '/holidays'
    | '/notes'
    | '/projects'
    | '/qr'
    | '/settings'
    | '/stopwatch'
    | '/subjects'
    | '/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiChatRoute: typeof AiChatRoute
  AssignmentsRoute: typeof AssignmentsRoute
  AttendanceRoute: typeof AttendanceRoute
  ExamsRoute: typeof ExamsRoute
  ExpensesRoute: typeof ExpensesRoute
  HolidaysRoute: typeof HolidaysRoute
  NotesRoute: typeof NotesRoute
  ProjectsRoute: typeof ProjectsRoute
  QrRoute: typeof QrRoute
  SettingsRoute: typeof SettingsRoute
  StopwatchRoute: typeof StopwatchRoute
  SubjectsRoute: typeof SubjectsRoute
  TimetableRoute: typeof TimetableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stopwatch': {
      id: '/stopwatch'
      path: '/stopwatch'
      fullPath: '/stopwatch'
      preLoaderRoute: typeof StopwatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiChatRoute: AiChatRoute,
  AssignmentsRoute: AssignmentsRoute,
  AttendanceRoute: AttendanceRoute,
  ExamsRoute: ExamsRoute,
  ExpensesRoute: ExpensesRoute,
  HolidaysRoute: HolidaysRoute,
  NotesRoute: NotesRoute,
  ProjectsRoute: ProjectsRoute,
  QrRoute: QrRoute,
  SettingsRoute: SettingsRoute,
  StopwatchRoute: StopwatchRoute,
  SubjectsRoute: SubjectsRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
