/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as TimetableRouteImport } from './routes/timetable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/attendance': typeof AttendanceRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/subjects': typeof SubjectsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/attendance': typeof AttendanceRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/subjects': typeof SubjectsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/attendance': typeof AttendanceRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/subjects': typeof SubjectsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/attendance'
    | '/exams'
    | '/expenses'
    | '/subjects'
    | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/attendance'
    | '/exams'
    | '/expenses'
    | '/subjects'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/attendance'
    | '/exams'
    | '/expenses'
    | '/subjects'
    | '/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  AttendanceRoute: typeof AttendanceRoute
  ExamsRoute: typeof ExamsRoute
  ExpensesRoute: typeof ExpensesRoute
  SubjectsRoute: typeof SubjectsRoute
  TimetableRoute: typeof TimetableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  AttendanceRoute: AttendanceRoute,
  ExamsRoute: ExamsRoute,
  ExpensesRoute: ExpensesRoute,
  SubjectsRoute: SubjectsRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
